export const enum Era {
  ANCIENT = 'ANCIENT',

  CLASSICAL = 'CLASSICAL',

  MEDIEVAL = 'MEDIEVAL',

  EARLY_MODERN = 'EARLY_MODERN',

  INDUSTRIAL = 'INDUSTRIAL',

  CONTEMPORARY = 'CONTEMPORARY',
}
